FROM ghcr.io/cyber-dojo-languages/ubuntu-build-essential-24-04:8ab6c08
LABEL maintainer=byran@adgico.co.uk
LABEL maintainer=jon@jaggersoft.com

ENV SWIFT_OS_MAJOR=24
ENV SWIFT_OS_MINOR=04
ENV SWIFT_VERSION=6.0.3

COPY install.sh .
RUN ./install.sh && rm -f install.sh

ENV PATH=/swift-${SWIFT_VERSION}-RELEASE-ubuntu${SWIFT_OS_MAJOR}.${SWIFT_OS_MINOR}/usr/bin:${PATH}
