FROM cyberdojofoundation/ubuntu-build-essential:18.04
LABEL maintainer=byran@adgico.co.uk
LABEL maintainer=jon@jaggersoft.com

ENV SWIFT_OS_MAJOR=18
ENV SWIFT_OS_MINOR=04
ENV SWIFT_VERSION=5.1.3

COPY install.sh .
RUN ./install.sh && rm -f install.sh

ENV PATH=/swift-${SWIFT_VERSION}-RELEASE-ubuntu${SWIFT_OS_MAJOR}.${SWIFT_OS_MINOR}/usr/bin:${PATH}
